### ISSUE TITLE
Rows disappear with scrollToIndex and overscanRowCount=0

### ISSUE THREAD

**Issue by fritz-c** [bvaughn/react-virtualized#305]
Reproduced here: https://plnkr.co/edit/gFk7uXNajnowcmzO0vD0

The combination of scrollToIndex, scrollToAlignment = (start|center), and overscanRowCount = 0 results in rows disappearing when the row whose index was specified cannot be placed at the start/center of the list without scrolling beyond the scrolling element's limit.

**Comment by bvaughn** [comment]
Hey @fritz-c,

Help me understand what I'm looking at. On my screen, the Plunker scrolls to the bottom of the list (as I think it should) when the scroll-to-index is too high.

<img width="309" alt="screen shot 2016-07-05 at 7 03 25 pm" src="https://cloud.githubusercontent.com/assets/29597/16605371/3665cc66-42e3-11e6-8275-d108f63e402a.png">

Am I misunderstanding what you're reporting? Am I seeing something different than you?

**Comment by fritz-c** [comment]
Hmm... I suppose it might be browser-dependent. Here's what I see on OS X 10.11.5 / Chrome 51:
![issue](https://cloud.githubusercontent.com/assets/4413963/16607031/fe3a3dc8-4377-11e6-8dd8-9d9aa2e8ac00.gif)

**Comment by babsonmatt** [comment]
OSX 10.11.3 / Chrome 51.0.2704.106 (64-bit)

![image](https://cloud.githubusercontent.com/assets/853220/16607110/a9f8cf16-430b-11e6-8521-63d04a5b583b.png)

**Comment by bvaughn** [comment]
I am running OS X 10.11.5. Interesting enough I _can_ reproduce this behavior on Firefox but not on my other browsers.

### Cannot reproduce
* Chrome 51.0.2704.103.
* Chromium 48.0.2553.0
* Safari 9.1.1

### Can reproduce
* Firefox 47.0

No immediate idea why OS X 10.11.3 would cause behavior like this.

**Comment by bvaughn** [comment]
Never mind. I've identified the issue. Thanks for the helpful Plnkr!

**Comment by bvaughn** [comment]
Fixed and released as 7.11.8.

Thanks again for the quality bug report!

**Comment by fritz-c** [comment]
Thanks for the speedy fix!

**Comment by pmbednarczyk** [comment]
This problem still occurs but in a little different scenario.
```    <List
            className="entry-group-list"
            height={height}
            width={width}
            rowHeight={cache.rowHeight}
            rowRenderer={renderEntryGroup}
            rowCount={entriesGroups.length}
            scrollToIndex={entriesGroups.length - 1}
            overscanRowCount={10}
          />
```

If  `entriesGroups.length - 1` in  `scrollToIndex` is bigger value than `overscanRowCount` value, then auto scrolling to last list element doesn't work.  Anyone know how to resolve this?
