### ISSUE TITLE
9.18.1 Kills build!

### ISSUE THREAD

**Issue by Kepro** [bvaughn/react-virtualized#989]
9.18.0 is working fine but today 9.18.0 start failing...

[INFO] Failed to compile.
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_AnimationTimeoutId' (40:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from 'prop-types';
[INFO] | export { bpfrpt_proptype_AnimationTimeoutId };
[INFO] | export { bpfrpt_proptype_AnimationTimeoutId };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_CellDataGetterParams' (117:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from "prop-types";
[INFO] | export { bpfrpt_proptype_CellDataGetterParams };
[INFO] | export { bpfrpt_proptype_CellDataGetterParams };
[INFO] | export { bpfrpt_proptype_CellRendererParams };
[INFO] | export { bpfrpt_proptype_CellRendererParams };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_CellMeasurerCache' (482:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from 'prop-types';
[INFO] | export { bpfrpt_proptype_CellMeasurerCache };
[INFO] | export { bpfrpt_proptype_CellMeasurerCache };
[INFO] | export { bpfrpt_proptype_Positioner };
[INFO] | export { bpfrpt_proptype_Positioner };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_CellPosition' (188:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from 'prop-types';
[INFO] | export { bpfrpt_proptype_CellPosition };
[INFO] | export { bpfrpt_proptype_CellPosition };
[INFO] | export { bpfrpt_proptype_CellRendererParams };
[INFO] | export { bpfrpt_proptype_CellRendererParams };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_Index' (45:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from "prop-types";
[INFO] | export { bpfrpt_proptype_Index };
[INFO] | export { bpfrpt_proptype_Index };
[INFO] | export { bpfrpt_proptype_PositionInfo };
[INFO] | export { bpfrpt_proptype_PositionInfo };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_RowRendererParams' (45:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from 'prop-types';
[INFO] | export { bpfrpt_proptype_RowRendererParams };
[INFO] | export { bpfrpt_proptype_RowRendererParams };
[INFO] | export { bpfrpt_proptype_RowRenderer };
[INFO] | export { bpfrpt_proptype_RowRenderer };
[INFO] 
[INFO] Module parse failed: Duplicate export 'bpfrpt_proptype_ScrollIndices' (11:9)
[INFO] You may need an appropriate loader to handle this file type.
[INFO] | import PropTypes from "prop-types";
[INFO] | export { bpfrpt_proptype_ScrollIndices };
[INFO] | export { bpfrpt_proptype_ScrollIndices };
[INFO]

**Comment by leanderhoedt** [comment]
Same problem here

**Comment by slavab89** [comment]
Same thing here, just noticed it

**Comment by chbdetta** [comment]
a lockfile saves the day.

**Comment by TrySound** [comment]
Fixed in 9.18.2

**Comment by nathanpower** [comment]
Lot's of warnings still present when using the commonjs build, imported like so:

```JS
import { List } from 'react-virtualized/dist/commonjs/List';
```

Would a new issue be better for this?

<details><summary>build warnings</summary><br>
WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
281:117-150 "export 'bpfrpt_proptype_NoContentRenderer' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
281:164-197 "export 'bpfrpt_proptype_NoContentRenderer' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
281:19-52 "export 'bpfrpt_proptype_NoContentRenderer' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
281:216-249 "export 'bpfrpt_proptype_NoContentRenderer' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
281:70-103 "export 'bpfrpt_proptype_NoContentRenderer' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
299:125-162 "export 'bpfrpt_proptype_OverscanIndicesGetter' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
299:176-213 "export 'bpfrpt_proptype_OverscanIndicesGetter' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
299:19-56 "export 'bpfrpt_proptype_OverscanIndicesGetter' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
299:232-269 "export 'bpfrpt_proptype_OverscanIndicesGetter' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
299:74-111 "export 'bpfrpt_proptype_OverscanIndicesGetter' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
312:137-161 "export 'bpfrpt_proptype_CellSize' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
312:180-204 "export 'bpfrpt_proptype_CellSize' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
312:19-43 "export 'bpfrpt_proptype_CellSize' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
312:61-85 "export 'bpfrpt_proptype_CellSize' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
312:99-123 "export 'bpfrpt_proptype_CellSize' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
328:101-126 "export 'bpfrpt_proptype_Alignment' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
328:140-165 "export 'bpfrpt_proptype_Alignment' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
328:184-209 "export 'bpfrpt_proptype_Alignment' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
328:19-44 "export 'bpfrpt_proptype_Alignment' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor

WARNING in ./node_modules/react-virtualized/dist/es/List/List.js
328:62-87 "export 'bpfrpt_proptype_Alignment' was not found in '../Grid'
 @ ./node_modules/react-virtualized/dist/es/List/List.js
 @ ./node_modules/react-virtualized/dist/es/List/index.js
 @ ./node_modules/react-virtualized/dist/es/index.js
 @ dll vendor
</details>

**Comment by Kepro** [comment]
@nathanpower did you try npm upgrade or yarn upgrade?

**Comment by nathanpower** [comment]
>@nathanpower did you try npm upgrade or yarn upgrade?

no, this is a fresh install using npm

**Comment by TrySound** [comment]
Temporary reverted last change in 9.18.3
